version: '3.8'

services:
  rag-chatbot:
    build: .
    ports:
      - "8501:8501"
      - "11434:11434"
    volumes:
      - ./uploaded_docs:/app/uploaded_docs  
      - database_data:/app/database      
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - HF_HUB_DISABLE_SYMLINKS_WARNING=1
    restart: unless-stopped
    entrypoint: /app/entrypoint.sh

  teacher-upload:
    build: .
    ports:
      - "8502:8502"
    volumes:
      - ./uploaded_docs:/app/uploaded_docs  
      - database_data:/app/database 
    restart: unless-stopped
    depends_on:
      - rag-chatbot
    command: >
      bash -c "
        sleep 10
        streamlit run upload.py --server.port=8502 --server.address=0.0.0.0
      "

volumes:
  ollama_data:
  database_data:  
  uploaded_docs: