version: '3.8'

services:
  chatbot-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - PORT=8000
      - OLLAMA_HOST=rag-chatbot:11434  # Point to your Ollama service
    ports:
      - "8000:8000"
    depends_on:
      - rag-chatbot

  rag-chatbot:
    build: .
    ports:
      - "11434:11434"  # Only expose Ollama port
    volumes:
      - azure_uploaded_docs:/app/uploaded_docs  
      - azure_database_data:/app/database      
      - azure_ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - HF_HUB_DISABLE_SYMLINKS_WARNING=1
    restart: unless-stopped
    entrypoint: /app/entrypoint.sh

  # For Azure deployment, we'll skip teacher-upload or deploy separately
  # teacher-upload:
  #   build: .
  #   ports:
  #     - "8502:8502"
  #   volumes:
  #     - azure_uploaded_docs:/app/uploaded_docs  
  #     - azure_database_data:/app/database 
  #   restart: unless-stopped
  #   depends_on:
  #     - rag-chatbot
  #   command: >
  #     bash -c "
  #       sleep 10
  #       streamlit run upload.py --server.port=8502 --server.address=0.0.0.0
  #     "

volumes:
  azure_ollama_data:
  azure_database_data:  
  azure_uploaded_docs: